---
- name: Deploy Food Delivery Application
  hosts: 13.235.76.210
  become: yes
  vars:
    app_repo: "https://github.com/thuongpham09112000/Food-Deliverry"
    node_version: "v18.18.0"
    db_username: "thuongpham"
    db_password: "123456789"
    db_name: "Food_Delivery"
  tasks:
    - name: Install Node.js
      yum:
        name: "nodejs"
        state: present

    - name: Clone application source code from GitHub
      git:
        repo: "{{ app_repo }}"
        dest: "/opt/food-delivery"
        version: "main"

    - name: Install Node.js dependencies
      npm:
        path: "/opt/food-delivery"
        state: present

    - name: Install MySQL client
      yum:
        name: "mysql"
        state: present

    - name: Configure MySQL connection
      template:
        src: "/path/to/your/mysql_config_template.cnf"
        dest: "/opt/food-delivery/mysql_config.cnf"
        owner: "root"
        group: "root"
        mode: "0644"
      vars:
        db_host: "localhost"
        db_username: "{{ db_username }}"
        db_password: "{{ db_password }}"
        db_name: "{{ db_name }}"

    - name: Setup database
      mysql_db:
        name: "{{ db_name }}"
        login_user: "{{ db_username }}"
        login_password: "{{ db_password }}"
        state: present

    - name: Import database schema
      mysql_db:
        name: "{{ db_name }}"
        login_user: "{{ db_username }}"
        login_password: "{{ db_password }}"
        state: import
        target: "/path/to/your/database/schema.sql"

    - name: Start Node.js application
      shell: |
        cd /opt/food-delivery
        NODE_ENV=production npm start
